### ISSUE TITLE
AttributeError: 'PerspectiveCamera' object has no attribute 'rot'

### ISSUE THREAD

**Issue by kentborg** [KeyWeeUsr/3DwithKivy#1]
04_movements.py blows up when I hit the 'a' key.

I think I have a version problem...what Kivy3 is the best? I don't see any tags for releases.

My Kivy3 is the most recent on github at commit 1c050b9bab from Dec 22 2016.

And:

kentborg@thinpan:~/python/3DwithKivy$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import kivy
[INFO   ] [Logger      ] Record log in /home/kentborg/.kivy/logs/kivy_17-06-30_16.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118]

**Comment by KeyWeeUsr** [comment]
Niko's Kivy3 doesn't have the required stuff I have in [my Kivy3 repo](https://github.com/KeyWeeUsr/kivy3) such as the content of the pull requests in the older repo. Try with my repo, that one should support even py3 without problems thanks to patches from @rense.

**Comment by kentborg** [comment]
Indeed, that fixed this problem... 

Thanks,

-kb
