### ISSUE TITLE
math.floor() used to index array in geometries.py, line 73 

### ISSUE THREAD

**Issue by kentborg** [KeyWeeUsr/3DwithKivy#2]
I deleted the floor() part and it no longer crashes.

But this is from a pretty old commit, makes me think I don't have the right code yet.

> 39bce596 kivy3/extras/geometries.py (Rense VanderHoek 2016-12-26 19:30:48 +0100 73)             normal = self._cube_normals[floor(n_idx / 2)]

I am on master branch, at commit 8c664cca (2 Feb 2017), in https://github.com/KeyWeeUsr/kivy3.

-kb

**Comment by KeyWeeUsr** [comment]
moved to https://github.com/KeyWeeUsr/kivy3/issues/1
